<?php
return [
  ['title' =>'电影片','id' => '1','shield' => 'false'],
  ['title' =>'连续剧','id' => '2','shield' => 'false'],
  ['title' =>'综艺片','id' => '3','shield' => 'false'],
  ['title' =>'动漫片','id' => '4','shield' => 'false'],
  ['title' =>'福利片','id' => '16','shield' => 'true'],
  ['title' =>'伦理片','id' => '17','shield' => 'true'],
  ['title' =>'音乐片','id' => '18','shield' => 'false'],
  ['title' =>'动作片','id' => '5','shield' => 'false'],
  ['title' =>'喜剧片','id' => '6','shield' => 'false'],
  ['title' =>'爱情片','id' => '7','shield' => 'false'],
  ['title' =>'科幻片','id' => '8','shield' => 'false'],
  ['title' =>'恐怖片','id' => '9','shield' => 'false'],
  ['title' =>'剧情片','id' => '10','shield' => 'false'],
  ['title' =>'战争片','id' => '11','shield' => 'false'],
  ['title' =>'国产剧','id' => '12','shield' => 'false'],
  ['title' =>'香港剧','id' => '13','shield' => 'false'],
  ['title' =>'韩国剧','id' => '14','shield' => 'false'],
  ['title' =>'欧美剧','id' => '15','shield' => 'false'],
  ['title' =>'台湾剧','id' => '19','shield' => 'false'],
  ['title' =>'日本剧','id' => '20','shield' => 'false'],
  ['title' =>'海外剧','id' => '21','shield' => 'false'],
];