<?php
return [
'api1' => 'http://127.0.0.13/api.html',
'api' => 'http://www.kukuzy.com/inc/api.php',
'template' => 'default',
'playerUrl' => 'https://www.hidove.cn/api/player/?url=',
'title' => 'Hidove影视',
'subtitle' => '全网大片一网打尽！',
'keywords' => 'Hidove,余生,电影,视频大全,在线高清电影,付费电影,免费电影,电视剧,电影,在线观看,VIP高清电影直播',
'description' => 'Hidove影视，是Hidove旗下专门做电视剧,电影等在线播放服务，本页面提供电影的相关内容。',
'favicon' => 'https://www.hidove.cn/favicon.ico',
'username' => 'admin',
'password' => 'c1bc9fd5e85637c3c03ae8e2bf2357f7',
'avatar' => 'http://q2.qlogo.cn/headimg_dl?dst_uin=821455965&spec=100',
'order' => 'true',
'cache' => 'false',
'cache-index' => 'true',
'cache-index-time' => '120',
'cache-sort' => 'true',
'cache-sort-time' => '5',
'cache-info' => 'true',
'cache-info-time' => '5',
'cache-search' => 'true',
'cache-search-time' => '5',
'foot-code' => '',
];